// This file sends http requests!
// VScode extension humao.rest-client
POST http://localhost:3000/insertAdvertisement/ HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "optionId": 1000000009,
            "companyId": 1000000001,
            "cost": 1000.00,
            "audienceReach": 4000,
            "adTypeName": "Fixed"
        },
        {
            "optionId": 1000000010,
            "companyId": 1000000001,
            "cost": 800.00,
            "audienceReach": 5000,
            "adTypeName": "Fixed"
        },
        {
            "optionId": 1000000011,
            "companyId": 1000000001,
            "cost": 100.00,
            "audienceReach": 200,
            "adTypeName": "Not Fixed"
        },
        {
            "optionId": 1000000012,
            "companyId": 1000000001,
            "cost": 5000.00,
            "audienceReach": 7000,
            "adTypeName": "Fixed"
        }
    ]
}

###

GET http://localhost:3000/basic/Alldata?companyId=1000000001&audienceReach=4000&page=1&pageSize=1
Content-Type: application/json

###

GET http://localhost:3000/basic/Alldata?companyId=1000000001&page=2&pageSize=5
Content-Type: application/json

###

GET http://localhost:3000/basic/Alldata?page=1&pageSize=2
Content-Type: application/json


###

GET http://localhost:3000/basic/Alldata
Content-Type: application/json