// http test Script
// Name: Wong En Ting Kelyn
// Name: Teh Huan Xi Kester
// Class: DIT/FT/2B/01

// This file sends http requests!
// VScode extension humao.rest-client
POST http://localhost:3000/basic/insert/ HTTP/1.1
Content-Type: application/json

{
    "data": [
        {
            "optionId": 1000000001,
            "companyId": 1000000001,
            "cost": 1000.00,
            "audienceCount": 4000,
            "adType": "Fixed"
        },
        {
            "optionId": 1000000002,
            "companyId": 1000000001,
            "cost": 800.00,
            "audienceCount": 5000,
            "adType": "Fixed"
        },
        {
            "optionId": 1000000003,
            "companyId": 1000000001,
            "cost": 100.00,
            "audienceCount": 200,
            "adType": "Not Fixed"
        },
        {
            "optionId": 1000000004,
            "companyId": 1000000002,
            "cost": 5000.00,
            "audienceCount": 7000,
            "adType": "Not Fixed"
        },
        {
            "optionId": 1000000005,
            "companyId": 1000000002,
            "cost": 5000.00,
            "audienceCount": 700,
            "adType": "Not Fixed"
        },
        {
            "optionId": 1000000006,
            "companyId": 1000000002,
            "cost": 5000.00,
            "audienceCount": 3000,
            "adType": "Not Fixed"
        }
    ]
}

###

POST http://localhost:3000/basic/insert/ HTTP/1.1
Content-Type: application/json

{
    "data": []
}

###
POST http://localhost:3000/basic/result HTTP/1.1
Content-Type: application/json

{
    "optionIds": ["1000000003","1000000004","1000000005","1000000006"],
    "budget": 1000
}

###
POST http://localhost:3000/basic/allChartData HTTP/1.1
Content-Type: application/json

{
    "optionIds": ["1000000002","1000000004","1000000005","1000000006"]
}